[package]
name = "world-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.16", features = ["derive"] }
env_logger = "0.11"
glam = "0.27"
log = "0.4"
noise = "0.9"
pollster = "0.3"
rayon = "1.10"
wgpu = "0.19"
winit = "0.29"
egui = "0.27"
